<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Staff;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $staff = [
            [
                "user_id" => 1,
                "department_id" => 1,
                "specialization" => "Cardiology",
                "qualification" => "MD Cardiology",
                "experience_years" => 10,
                "license_number" => "LIC123456",
                "date_of_birth" => "1980-05-15",
                "gender" => "male",
                "phone_number" => "555-1234",
                "temporary_address" => "123 Temporary St, City",
                "permanent_address" => "456 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Day Shift",
                "emergency_contact_name" => "Jane Doe",
                "emergency_contact_relationship" => "Spouse",
                "emergency_contact_phone" => "555-5678",
            "salary" => 120000,
            ],[
                "user_id" => 2,
                "department_id" => 2,
                "specialization" => "Neurology",
                "qualification" => "MD Neurology",
                "experience_years" => 8,
                "license_number" => "LIC234567",
                "date_of_birth" => "1982-07-20",
                "gender" => "female",
                "phone_number" => "555-2345",
                "temporary_address" => "789 Temporary St, City",
                "permanent_address" => "101 Permanent Ave, City",
                "employment_status" => "part-time",
                "shift_details" => "Night Shift",
                "emergency_contact_name" => "John Smith",
                "emergency_contact_relationship" => "Brother",
                "emergency_contact_phone" => "555-6789",
            "salary" => 110000,
            ],[
                "user_id" => 3,
                "department_id" => 3,
                "specialization" => "Pediatrics",
                "qualification" => "MD Pediatrics",
                "experience_years" => 5,
                "license_number" => "LIC345678",
                "date_of_birth" => "1985-09-10",
                "gender" => "female",
                "phone_number" => "555-3456",
                "temporary_address" => "234 Temporary St, City",
                "permanent_address" => "567 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Evening Shift",
                "emergency_contact_name" => "Emily Johnson",
                "emergency_contact_relationship" => "Sister",
            "emergency_contact_phone" => "555-7890",
            "salary" => 100000,
            ],[
                "user_id" => 4,
                "department_id" => 4,
                "specialization" => "Orthopedics",
                "qualification" => "MD Orthopedics",
                "experience_years" => 12,
                "license_number" => "LIC456789",
                "date_of_birth" => "1978-11-25",
                "gender" => "male",
                "phone_number" => "555-4567",
                "temporary_address" => "345 Temporary St, City",
                "permanent_address" => "678 Permanent Ave, City",
                "employment_status" => "contract",
                "shift_details" => "Weekend Shift",
                "emergency_contact_name" => "Michael Brown",
                "emergency_contact_relationship" => "Friend",
            "emergency_contact_phone" => "555-8901",
            "salary" => 130000,
            ],[
                "user_id" => 5,
                "department_id" => 5,
                "specialization" => "Dermatology",
                "qualification" => "MD Dermatology",
                "experience_years" => 7,
                "license_number" => "LIC567890",
                "date_of_birth" => "1983-03-30",
                "gender" => "female",
                "phone_number" => "555-5678",
                "temporary_address" => "456 Temporary St, City",
                "permanent_address" => "789 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Day Shift",
                "emergency_contact_name" => "Sarah Williams",
                "emergency_contact_relationship" => "Mother",
            "emergency_contact_phone" => "555-9012",
            "salary" => 115000,
            ],[
                "user_id" => 6,
                "department_id" => 5,
                "specialization" => "Gastroenterology",
                "qualification" => "MD Gastroenterology",
                "experience_years" => 9,
                "license_number" => "LIC678901",
                "date_of_birth" => "1981-02-14",
                "gender" => "male",
                "phone_number" => "555-6789",
                "temporary_address" => "567 Temporary St, City",
                "permanent_address" => "890 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Day Shift",
                "emergency_contact_name" => "Laura Green",
                "emergency_contact_relationship" => "Wife",
                "emergency_contact_phone" => "555-0123",
            "salary" => 125000,
            ],[
                "user_id" => 7,
                "department_id" => 4,
                "specialization" => "Oncology",
                "qualification" => "MD Oncology",
                "experience_years" => 11,
                "license_number" => "LIC789012",
                "date_of_birth" => "1979-08-22",
                "gender" => "female",
                "phone_number" => "555-7890",
                "temporary_address" => "678 Temporary St, City",
                "permanent_address" => "901 Permanent Ave, City",
                "employment_status" => "part-time",
                "shift_details" => "Night Shift",
                "emergency_contact_name" => "David White",
                "emergency_contact_relationship" => "Husband",
                "emergency_contact_phone" => "555-1234",
            "salary" => 135000,
            ],[
                "user_id" => 8,
                "department_id" => 3,
                "specialization" => "Radiology",
                "qualification" => "MD Radiology",
                "experience_years" => 6,
                "license_number" => "LIC890123",
                "date_of_birth" => "1984-12-05",
                "gender" => "male",
                "phone_number" => "555-8901",
                "temporary_address" => "789 Temporary St, City",
                "permanent_address" => "012 Permanent Ave, City",
                "employment_status" => "contract",
                "shift_details" => "Weekend Shift",
                "emergency_contact_name" => "Anna Black",
                "emergency_contact_relationship" => "Sister",
                "emergency_contact_phone" => "555-2345",
            "salary" => 105000,
           ], [
                "user_id" => 9,
                "department_id" => 2,
                "specialization" => "Urology",
                "qualification" => "MD Urology",
                "experience_years" => 13,
                "license_number" => "LIC901234",
                "date_of_birth" => "1977-04-18",
                "gender" => "female",
                "phone_number" => "555-9012",
                "temporary_address" => "890 Temporary St, City",
                "permanent_address" => "123 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Evening Shift",
                "emergency_contact_name" => "James Grey",
                "emergency_contact_relationship" => "Father",
                "emergency_contact_phone" => "555-3456",
                "salary" => 140000,
            ],
            [
                "user_id" => 10,
                "department_id" => 3,
                "specialization" => "Ophthalmology",
                "qualification" => "MD Ophthalmology",
                "experience_years" => 4,
                "license_number" => "LIC012345",
                "date_of_birth" => "1986-06-25",
                "gender" => "male",
                "phone_number" => "555-0123",
                "temporary_address" => "901 Temporary St, City",
                "permanent_address" => "234 Permanent Ave, City",
                "employment_status" => "part-time",
                "shift_details" => "Day Shift",
                "emergency_contact_name" => "Karen Blue",
                "emergency_contact_relationship" => "Mother",
            "emergency_contact_phone" => "555-4567",
            "salary" => 95000,
          ],
            [
                "user_id" => 11,
                "department_id" => 5,
                "specialization" => "Endocrinology",
                "qualification" => "MD Endocrinology",
                "experience_years" => 15,
                "license_number" => "LIC123789",
                "date_of_birth" => "1975-01-10",
                "gender" => "female",
                "phone_number" => "555-1235",
                "temporary_address" => "1234 Temporary St, City",
                "permanent_address" => "4567 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Day Shift",
                "emergency_contact_name" => "Paul Red",
                "emergency_contact_relationship" => "Husband",
            "emergency_contact_phone" => "555-5679",
            "salary" => 145000,
         ],
            [
                "user_id" => 12,
                "department_id" => 4,
                "specialization" => "Nephrology",
                "qualification" => "MD Nephrology",
                "experience_years" => 14,
                "license_number" => "LIC234890",
                "date_of_birth" => "1976-03-22",
                "gender" => "male",
                "phone_number" => "555-2346",
                "temporary_address" => "2345 Temporary St, City",
                "permanent_address" => "6789 Permanent Ave, City",
                "employment_status" => "full-time",
                "shift_details" => "Night Shift",
                "emergency_contact_name" => "Linda Green",
                "emergency_contact_relationship" => "Wife",
                "emergency_contact_phone" => "555-6780",
            "salary" => 150000
        ],
        ];

        foreach ($staff as $member) {
            Staff::create($member);
        }
    }
}
